### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by wcjqwq** [tamilpp25/YSDispatch#1]
![image](https://user-images.githubusercontent.com/92256031/230621814-c7e848a0-e899-4d03-ab82-49003817a1ce.png)
I work normally on Windows

Address already in use on Linux

I took a look and felt that the address was not being used (it should be

**Comment by tamilpp25** [comment]
That's weird, can you check with some other port? by default it was set to 443 since it was HTTPS

**Comment by wcjqwq** [comment]
If it is port 443, there is no program on my server using port 443

**Comment by wcjqwq** [comment]
![image](https://user-images.githubusercontent.com/92256031/230760987-1deb34f5-4f31-4f2b-bbd5-a34c8c096c89.png)

**Comment by tamilpp25** [comment]
Can you check the latest commit? It should work

**Comment by wcjqwq** [comment]
I am now working normally

**Comment by wcjqwq** [comment]
![image](https://user-images.githubusercontent.com/92256031/230887004-62ca51d5-fde6-4fa1-af20-99fb8d5b7b95.png)
